---
# defaults file for kubernetes-alpine

# If master or worker
kubernetes_node_type: none
kubernetes_first_master: none

# Kubeadm params
kubernetes_pods_cidr: 172.18.0.0/17
kubernetes_service_cidr: 172.18.128.0/17

# Cni deploy
kubernetes_cni_yaml: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
